"""Add Feature Flag Domain Models

Revision ID: fbd3d84ac4a0
Revises: 002_create_tenancy_tables
Create Date: 2026-06-05 18:04:41.050414

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fbd3d84ac4a0'
down_revision: str | None = '002_create_tenancy_tables'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('previous_state', sa.JSON(), nullable=True),
    sa.Column('new_state', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_events_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_table('feature_flags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_feature_flags_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_flags'))
    )
    op.create_index('idx_ff_key_project_active', 'feature_flags', ['project_id', 'key'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_table('flag_variations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('feature_flag_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['feature_flag_id'], ['feature_flags.id'], name=op.f('fk_flag_variations_feature_flag_id_feature_flags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flag_variations'))
    )
    op.create_table('feature_flag_environments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('feature_flag_id', sa.Uuid(), nullable=False),
    sa.Column('environment_id', sa.Uuid(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('default_serve_variation_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['default_serve_variation_id'], ['flag_variations.id'], name=op.f('fk_feature_flag_environments_default_serve_variation_id_flag_variations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name=op.f('fk_feature_flag_environments_environment_id_environments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feature_flag_id'], ['feature_flags.id'], name=op.f('fk_feature_flag_environments_feature_flag_id_feature_flags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_flag_environments'))
    )
    op.create_index('idx_ff_env_unique', 'feature_flag_environments', ['feature_flag_id', 'environment_id'], unique=True)
    op.create_table('rollout_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('feature_flag_environment_id', sa.Uuid(), nullable=False),
    sa.Column('serve_variation_id', sa.Uuid(), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feature_flag_environment_id'], ['feature_flag_environments.id'], name=op.f('fk_rollout_rules_feature_flag_environment_id_feature_flag_environments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['serve_variation_id'], ['flag_variations.id'], name=op.f('fk_rollout_rules_serve_variation_id_flag_variations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rollout_rules'))
    )
    op.create_table('targeting_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('feature_flag_environment_id', sa.Uuid(), nullable=False),
    sa.Column('attribute', sa.String(length=255), nullable=False),
    sa.Column('operator', sa.String(length=50), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('serve_variation_id', sa.Uuid(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feature_flag_environment_id'], ['feature_flag_environments.id'], name=op.f('fk_targeting_rules_feature_flag_environment_id_feature_flag_environments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['serve_variation_id'], ['flag_variations.id'], name=op.f('fk_targeting_rules_serve_variation_id_flag_variations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_targeting_rules'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('targeting_rules')
    op.drop_table('rollout_rules')
    op.drop_index('idx_ff_env_unique', table_name='feature_flag_environments')
    op.drop_table('feature_flag_environments')
    op.drop_table('flag_variations')
    op.drop_index('idx_ff_key_project_active', table_name='feature_flags', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_table('feature_flags')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
